import { NextResponse } from "next/server";
import { requireSessionUser } from "@/lib/session-user";

function pdfText(value: unknown) {
  return String(value ?? "")
    .replace(/[\\()]/g, "\\$&")
    .replace(/[^\x20-\x7E]/g, "");
}

function buildPdf(lines: string[]) {
  const objects: string[] = [];
  const content = [
    "BT",
    "/F1 14 Tf",
    "50 790 Td",
    ...lines.flatMap((line, index) => [
      index === 0 ? "" : "0 -16 Td",
      `(${pdfText(line)}) Tj`,
    ]).filter(Boolean),
    "ET",
  ].join("\n");

  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj");
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj");
  objects.push("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj");
  objects.push("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj");
  objects.push(`5 0 obj\n<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream\nendobj`);

  const header = "%PDF-1.4\n";
  let body = "";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(header + body, "utf8"));
    body += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(header + body, "utf8");
  const xref = [
    "xref",
    `0 ${objects.length + 1}`,
    "0000000000 65535 f ",
    ...offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n `),
    "trailer",
    `<< /Size ${objects.length + 1} /Root 1 0 R >>`,
    "startxref",
    String(xrefOffset),
    "%%EOF",
  ].join("\n");

  return Buffer.from(`${header}${body}${xref}`, "utf8");
}

function linesFromArray(label: string, values: unknown) {
  const items = Array.isArray(values) ? values : [];
  if (!items.length) return [`${label}: None recorded`];
  return [
    `${label}:`,
    ...items.slice(0, 8).map((item, index) => `${index + 1}. ${String(item).slice(0, 110)}`),
  ];
}

export async function GET() {
  const { supabase, user, error } = await requireSessionUser(["org_admin", "manager", "coordinator", "superadmin"]);
  if (error || !user) return error;

  const { data: pack } = await supabase
    .from("cqc_evidence_packs")
    .select("*")
    .eq("organisation_id", user.organisation_id)
    .maybeSingle();

  if (!pack) {
    return NextResponse.json({ error: "No evidence pack found. Generate one first." }, { status: 404 });
  }

  const evidence = (pack.evidence_by_standard ?? {}) as Record<string, { score?: number; strengths?: string[]; gaps?: string[]; evidence_count?: number }>;
  const lines = [
    "CAREROOT CQC EVIDENCE PACK",
    "",
    `Generated: ${new Date().toLocaleDateString("en-GB")}`,
    `Last updated: ${pack.last_updated_at ? new Date(pack.last_updated_at).toLocaleString("en-GB") : "Not recorded"}`,
    `Overall score: ${pack.overall_compliance_score ?? "N/A"}`,
    `Inspection ready: ${pack.inspection_ready ? "Yes" : "No"}`,
    "",
    `Safe: ${pack.safe_score ?? "N/A"}`,
    `Effective: ${pack.effective_score ?? "N/A"}`,
    `Caring: ${pack.caring_score ?? "N/A"}`,
    `Responsive: ${pack.responsive_score ?? "N/A"}`,
    `Well-led: ${pack.well_led_score ?? "N/A"}`,
    "",
    ...linesFromArray("Top gaps", pack.gaps),
    "",
    ...Object.entries(evidence).flatMap(([standard, detail]) => [
      `${standard}: score ${detail?.score ?? "N/A"} | evidence ${detail?.evidence_count ?? 0}`,
      ...linesFromArray("Strengths", detail?.strengths),
      ...linesFromArray("Gaps", detail?.gaps),
      "",
    ]),
    "Generated by Careroot Care Management Platform",
  ].slice(0, 44);

  const pdf = buildPdf(lines);

  return new NextResponse(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=\"cqc-evidence-pack.pdf\"",
      "Content-Length": String(pdf.length),
    },
  });
}
