-- Migration 43: Handover Notes
-- Synthesised from shift data — raw shift_logs NEVER accessible to incoming worker
-- Outgoing worker must sign off before handover publishes
-- Incoming worker must confirm read before shift access fully opens

CREATE TABLE IF NOT EXISTS handover_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id uuid REFERENCES shifts(id),
  client_id uuid REFERENCES clients(id),
  outgoing_staff_id uuid REFERENCES users(id),
  incoming_staff_id uuid REFERENCES users(id),

  -- SYNTHESISED CONTENT
  -- Generated by system from shift structured data
  -- Raw logs NEVER included or visible to incoming worker
  current_status text NOT NULL,
  key_events text,
  nutrition_summary text,
  medication_summary text,
  actions_for_incoming_worker text,
  triggers_activated_this_shift text,

  -- OUTGOING WORKER DIGITAL SIGN-OFF
  -- Required before handover publishes to incoming worker
  outgoing_approved_at timestamptz,

  -- INCOMING WORKER CONFIRMATION
  -- Required before shift access fully opens
  incoming_read_confirmed_at timestamptz,

  server_timestamp timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_handover_notes_shift ON handover_notes(shift_id);
CREATE INDEX IF NOT EXISTS idx_handover_notes_client ON handover_notes(client_id);
CREATE INDEX IF NOT EXISTS idx_handover_notes_incoming ON handover_notes(incoming_staff_id);

ALTER TABLE handover_notes ENABLE ROW LEVEL SECURITY;

-- Outgoing worker can see and approve their own handovers
CREATE POLICY handover_outgoing ON handover_notes
  FOR ALL USING (outgoing_staff_id = auth.uid());

-- Incoming worker can see (but not edit) handovers addressed to them
-- only once outgoing has approved
CREATE POLICY handover_incoming ON handover_notes
  FOR SELECT USING (
    incoming_staff_id = auth.uid()
    AND outgoing_approved_at IS NOT NULL
  );

-- Managers see all handovers in their org
CREATE POLICY handover_manager ON handover_notes
  FOR ALL USING (
    (SELECT role FROM users WHERE id = auth.uid()) IN ('superadmin', 'org_admin', 'manager', 'coordinator')
    AND outgoing_staff_id IN (SELECT id FROM users WHERE organisation_id = (SELECT organisation_id FROM users WHERE id = auth.uid()))
  );
